name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Godot
      uses: firebelley/godot-export@v5
      with:
        godot-version: 4.3
        export-preset: "Android"
        use-godot-mono: false

    - name: Build Android APK
      run: |
        mkdir -p build/android
        godot --headless --export-release "Android" build/android/Cosmic-Stroje.apk

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Cosmic-Stroje-Android
        path: build/android/Cosmic-Stroje.apk
